name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true
      - name: clean
        run: cargo clean
      - name: fmt
        run: rustup component add rustfmt && cargo fmt -- --check
      - name: clippy
        run: rustup component add clippy && cargo clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
